language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 12.18.3

cache: yarn

defaults: &defaults
  install:
    # install dependencies
    - yarn install

jobs:
  include:
    - stage: test
      privder: script
      script: yarn test
    - stage: build
      provider: script
      script: yarn build:prod
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run semantic-release
