language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 12.18.3

cache: yarn

defaults: &defaults
  install:
    # install dependencies
    - yarn install

  # script:
  #   #   ## print all Travis environment variables for debugging
  #   # - $(npm bin)/print-env TRAVIS
  #   # - yarn run start
  #   - yarn run semantic-release
  #   # - yarn run cy:run -- --record --parallel --group $STAGE_NAME
  #   # after all tests finish running we need
  #   # to kill all background jobs (like "npm start &")
  #   # - kill $(jobs -p) || true

jobs:
  include:
    # # we have multiple jobs to execute using just a single stage
    # # but we can pass group name via environment variable to Cypress test runner
    - stage: test
      env:
        - STAGE_NAME="1x-electron on Travis CI"
      <<: *defaults
    # run tests in parallel by including several test jobs with same name variable
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn run semantic-release
    # - stage: test
    #   env:
    #     - STAGE_NAME="4x-electron on Travis CI"
    #   <<: *defaults
    # - stage: test
    #   env:
    #     - STAGE_NAME="4x-electron on Travis CI"
    #   <<: *defaults
