# This is a basic workflow that is manually triggered

name: Build & Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # Trigger the workflow on push or pull request,
  push:
    branches-ignore:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  install-test-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/master
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Jest test
        run: yarn test
      - name: Build
        run: yarn build:prod
